// One-time precompute script (ARCHITECTURE-SPINE AD-10). Runs the Engine
// once per Pokemon and writes the static result to src/data/combos.ts. NOT
// part of the app bundle and never imported by app code — the UI reads
// combos.ts only, never src/engine/.
//
// One canonical combo list per Pokemon (AD-8): category never changes
// scoring/ranking (the real game's category bonus feeds a competitive,
// opponent-dependent Voltage meter this project doesn't simulate), so there
// is nothing to precompute per-mode.
//
// Also precomputes `conditionalCombos` (AD-13) — a separate best-case
// ceiling list assuming favorable turn-order luck on slots no move
// guarantees. Never merged with `combos`; always a distinct list.
//
// Also precomputes `combosNoEgg`/`conditionalCombosNoEgg` (AD-14) — the same
// two searches, but over each Pokemon's learnable pool minus its egg moves,
// for players who haven't bred/traded for them. `combos`/`conditionalCombos`
// (the "with egg moves" variants) also get `eggSwaps` attached per result,
// precomputed here (never computed live by the UI, per the user's explicit
// choice to keep AD-1 strict rather than let the UI call the Engine live).
//
// Also precomputes `levelSwaps` on every result in all four lists (AD-15) —
// same-effect substitutes for any slot whose only way to learn it is
// level-up, so the UI can show what's actually usable at a given in-game
// level without a separate precomputed list per level (which would be
// combinatorially wasteful — levels run 1-100).
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { findBestCombos, findBestConditionalCombos } from '../src/engine/combo-engine.ts';
import { moves } from '../src/data/moves.ts';
import { pokemon } from '../src/data/pokemon.ts';
import type { Move, PrecomputedCombos, PrecomputedConditionalCombos } from '../src/data/types.ts';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DATA_DIR = path.resolve(__dirname, '../src/data');

async function main(): Promise<void> {
  if (pokemon.length === 0) {
    throw new Error('precompute-combos: pokemon dataset is empty — refusing to write combos.ts');
  }

  const result: PrecomputedCombos = {};
  const noEggResult: PrecomputedCombos = {};
  const conditionalResult: PrecomputedConditionalCombos = {};
  const conditionalNoEggResult: PrecomputedConditionalCombos = {};
  let done = 0;
  const start = Date.now();

  for (const p of pokemon) {
    if (result[p.id]) {
      throw new Error(`precompute-combos: duplicate Pokemon id ${p.id} — refusing to silently overwrite`);
    }
    const learnable = p.learnableMoveIds
      .map((id) => {
        const move = moves[id];
        if (!move) console.warn(`[precompute] "${p.name}" (#${p.id}) references unknown move id "${id}"`);
        return move;
      })
      .filter((m): m is Move => m !== undefined);
    const eggMoveIds = new Set(p.eggMoveIds);
    const learnableNoEgg = learnable.filter((m) => !eggMoveIds.has(m.id));
    const moveOrigins = new Map(Object.entries(p.moveOrigins));

    result[p.id] = findBestCombos(learnable, { topN: 5, eggMoveIds, moveOrigins });
    noEggResult[p.id] = findBestCombos(learnableNoEgg, { topN: 5, moveOrigins });
    conditionalResult[p.id] = findBestConditionalCombos(learnable, { topN: 5, eggMoveIds, moveOrigins });
    conditionalNoEggResult[p.id] = findBestConditionalCombos(learnableNoEgg, { topN: 5, moveOrigins });

    // Sanity check (AD-13): the conditional search is a strict superset of
    // the guaranteed search's achievable contexts, so its best score can
    // never be lower — a violation would mean the two engines disagree.
    for (const [best, conditionalBest, label] of [
      [result[p.id][0]?.totalScore ?? -Infinity, conditionalResult[p.id][0]?.totalScore ?? -Infinity, 'with egg moves'],
      [noEggResult[p.id][0]?.totalScore ?? -Infinity, conditionalNoEggResult[p.id][0]?.totalScore ?? -Infinity, 'without egg moves'],
    ] as const) {
      if (conditionalBest < best) {
        throw new Error(
          `precompute-combos: "${p.name}" (#${p.id}, ${label}) conditional best (${conditionalBest}) is lower than guaranteed best (${best}) — the two engines disagree`,
        );
      }
    }

    done++;
    if (done % 50 === 0) {
      console.log(`  -> ${done}/${pokemon.length} Pokemon (${((Date.now() - start) / 1000).toFixed(1)}s elapsed)`);
    }
  }

  const missing = pokemon.filter(
    (p) => !result[p.id] || !noEggResult[p.id] || !conditionalResult[p.id] || !conditionalNoEggResult[p.id],
  );
  if (missing.length > 0) {
    throw new Error(`Missing precomputed combos for ${missing.length} Pokemon — refusing to write a partial dataset`);
  }

  const lines: string[] = [
    '// AUTO-GENERATED by scripts/precompute-combos.ts — do not edit by hand.',
    '// Regenerate with: npm run precompute:combos',
    "import type { PrecomputedCombos, PrecomputedConditionalCombos } from './types.ts';",
    '',
    `export const combos: PrecomputedCombos = ${JSON.stringify(result)};`,
    '',
    `export const combosNoEgg: PrecomputedCombos = ${JSON.stringify(noEggResult)};`,
    '',
    `export const conditionalCombos: PrecomputedConditionalCombos = ${JSON.stringify(conditionalResult)};`,
    '',
    `export const conditionalCombosNoEgg: PrecomputedConditionalCombos = ${JSON.stringify(conditionalNoEggResult)};`,
    '',
  ];
  await writeFile(path.join(DATA_DIR, 'combos.ts'), lines.join('\n'), 'utf-8');

  console.log(`Wrote src/data/combos.ts for ${pokemon.length} Pokemon in ${((Date.now() - start) / 1000).toFixed(1)}s`);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
